### ISSUE TITLE
Slow loading bug, buying and feature request

### ISSUE THREAD

**Issue by Valus3000** [LinuxndroidTeam/DroidSpy2#2]
1. **Droidspy 2 is extremely slow in loading and showing the clients.** Other Android RAT loads clients only a few seconds. Droidspy 2 loads users random time, sometime 8-10 minutes. And this is on same dns/ip and port as other RAT when I was testing. Even on direct IP it takes forever to load. I am currently editing this post and 15mins has past and it still haven't load any clients. Closing off and re-opening sometimes fixes it, but not all the time. I will run Wireshark and see what is being access

2. Droidspy2 need an option to **re-enable accessibility** as when user/client turned it off, you cannot hear microphone audio again. I am currently experiencing this.
Additionally, the app icon doesnt hide when install and run. This is on Samsung Galaxy A series with Android 12. A fallback feature would be nice to fix this, such as when the client launch/open the app, it will open another app (google store) or link. (Making it seems legit)

3. I saw you also post Craxsrat-Lifetime even though that is made by EVLF_DEV . I am confuse which between Droidspy2 and craxrat is the best. Did you edit craxsrat leaked source code and remade it?

4.  Is edit socket, the same as if I build an apk and input the dns/ip and port. Is this option able to update the apk port and ip listening on the phone itself? If not, would it be possible to implement a feature like it reads not only from dns/ip but can fetch a file from github or pastebin that updates the dns addresses. Doubt very much, but thought I would ask cause I remember Async had a feature like this for windows.

5. A list of any custom terminal command would be nice if added to readme or the files itself for reference.

**Comment by LinuxndroidTeam** [comment]
Thanks for your feedback, 
**DroidSpy2 ** is take few time to show android connections , iam work for better socket code. and if you want craxsrat, then you can try it for sure, because craxsrat is work better all version android,

**What Additional Feature Our Craxsrat** This Craxsrat original by EVLF. this craxsrat additional is fud, and best way to use production level like WAN. And How to bind Manual Other APK. compleate Video Course How to do.

So i hope I answare Your Issues. if face any doubt feel free contact, Have A Nice Day.
